// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[owner]/[repo]" | "/[owner]/[repo]/[branch]" | "/[owner]/[repo]/[branch]/actions" | "/[owner]/[repo]/[branch]/cache" | "/[owner]/[repo]/[branch]/collaborators" | "/[owner]/[repo]/[branch]/collection/[name]" | "/[owner]/[repo]/[branch]/collection/[name]/edit/[path]" | "/[owner]/[repo]/[branch]/collection/[name]/new" | "/[owner]/[repo]/[branch]/configuration" | "/[owner]/[repo]/[branch]/file/[name]" | "/[owner]/[repo]/[branch]/media/[name]" | "/[owner]/[repo]/[branch]/settings" | "/admin" | "/auth/redirect" | "/settings" | "/sign-in" | "/sign-in/collaborator"
type AppRouteHandlerRoutes = "/api/[owner]/[repo]/[branch]/actions" | "/api/[owner]/[repo]/[branch]/actions/[runId]" | "/api/[owner]/[repo]/[branch]/branches" | "/api/[owner]/[repo]/[branch]/cache" | "/api/[owner]/[repo]/[branch]/collections/[name]" | "/api/[owner]/[repo]/[branch]/entries/[path]" | "/api/[owner]/[repo]/[branch]/entries/[path]/history" | "/api/[owner]/[repo]/[branch]/files/[path]" | "/api/[owner]/[repo]/[branch]/files/[path]/rename" | "/api/[owner]/[repo]/[branch]/media/[name]/[path]" | "/api/[owner]/[repo]/[branch]/references/[name]" | "/api/app/version" | "/api/auth/[...all]" | "/api/collaborator-invites/[token]" | "/api/collaborators/[...slug]" | "/api/github-app/install" | "/api/repos/[owner]" | "/api/webhook/github"
type PageRoutes = never
type LayoutRoutes = "/" | "/[owner]/[repo]" | "/[owner]/[repo]/[branch]" | "/sign-in"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[owner]/[repo]": { "owner": string; "repo": string; }
  "/[owner]/[repo]/[branch]": { "owner": string; "repo": string; "branch": string; }
  "/[owner]/[repo]/[branch]/actions": { "owner": string; "repo": string; "branch": string; }
  "/[owner]/[repo]/[branch]/cache": { "owner": string; "repo": string; "branch": string; }
  "/[owner]/[repo]/[branch]/collaborators": { "owner": string; "repo": string; "branch": string; }
  "/[owner]/[repo]/[branch]/collection/[name]": { "owner": string; "repo": string; "branch": string; "name": string; }
  "/[owner]/[repo]/[branch]/collection/[name]/edit/[path]": { "owner": string; "repo": string; "branch": string; "name": string; "path": string; }
  "/[owner]/[repo]/[branch]/collection/[name]/new": { "owner": string; "repo": string; "branch": string; "name": string; }
  "/[owner]/[repo]/[branch]/configuration": { "owner": string; "repo": string; "branch": string; }
  "/[owner]/[repo]/[branch]/file/[name]": { "owner": string; "repo": string; "branch": string; "name": string; }
  "/[owner]/[repo]/[branch]/media/[name]": { "owner": string; "repo": string; "branch": string; "name": string; }
  "/[owner]/[repo]/[branch]/settings": { "owner": string; "repo": string; "branch": string; }
  "/admin": {}
  "/api/[owner]/[repo]/[branch]/actions": { "owner": string; "repo": string; "branch": string; }
  "/api/[owner]/[repo]/[branch]/actions/[runId]": { "owner": string; "repo": string; "branch": string; "runId": string; }
  "/api/[owner]/[repo]/[branch]/branches": { "owner": string; "repo": string; "branch": string; }
  "/api/[owner]/[repo]/[branch]/cache": { "owner": string; "repo": string; "branch": string; }
  "/api/[owner]/[repo]/[branch]/collections/[name]": { "owner": string; "repo": string; "branch": string; "name": string; }
  "/api/[owner]/[repo]/[branch]/entries/[path]": { "owner": string; "repo": string; "branch": string; "path": string; }
  "/api/[owner]/[repo]/[branch]/entries/[path]/history": { "owner": string; "repo": string; "branch": string; "path": string; }
  "/api/[owner]/[repo]/[branch]/files/[path]": { "owner": string; "repo": string; "branch": string; "path": string; }
  "/api/[owner]/[repo]/[branch]/files/[path]/rename": { "owner": string; "repo": string; "branch": string; "path": string; }
  "/api/[owner]/[repo]/[branch]/media/[name]/[path]": { "owner": string; "repo": string; "branch": string; "name": string; "path": string; }
  "/api/[owner]/[repo]/[branch]/references/[name]": { "owner": string; "repo": string; "branch": string; "name": string; }
  "/api/app/version": {}
  "/api/auth/[...all]": { "all": string[]; }
  "/api/collaborator-invites/[token]": { "token": string; }
  "/api/collaborators/[...slug]": { "slug": string[]; }
  "/api/github-app/install": {}
  "/api/repos/[owner]": { "owner": string; }
  "/api/webhook/github": {}
  "/auth/redirect": {}
  "/settings": {}
  "/sign-in": {}
  "/sign-in/collaborator": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[owner]/[repo]": never
  "/[owner]/[repo]/[branch]": never
  "/sign-in": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
