// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(auth)/auth/redirect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/redirect">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/auth/redirect/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/sign-in/collaborator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in/collaborator">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/sign-in/collaborator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/[owner]/[repo]/[branch]/actions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[owner]/[repo]/[branch]/actions">> = Specific
  const handler = {} as typeof import("../../../app/(main)/[owner]/[repo]/[branch]/actions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/[owner]/[repo]/[branch]/cache/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[owner]/[repo]/[branch]/cache">> = Specific
  const handler = {} as typeof import("../../../app/(main)/[owner]/[repo]/[branch]/cache/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/[owner]/[repo]/[branch]/collaborators/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[owner]/[repo]/[branch]/collaborators">> = Specific
  const handler = {} as typeof import("../../../app/(main)/[owner]/[repo]/[branch]/collaborators/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/[owner]/[repo]/[branch]/collection/[name]/edit/[path]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[owner]/[repo]/[branch]/collection/[name]/edit/[path]">> = Specific
  const handler = {} as typeof import("../../../app/(main)/[owner]/[repo]/[branch]/collection/[name]/edit/[path]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/[owner]/[repo]/[branch]/collection/[name]/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[owner]/[repo]/[branch]/collection/[name]/new">> = Specific
  const handler = {} as typeof import("../../../app/(main)/[owner]/[repo]/[branch]/collection/[name]/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/[owner]/[repo]/[branch]/collection/[name]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[owner]/[repo]/[branch]/collection/[name]">> = Specific
  const handler = {} as typeof import("../../../app/(main)/[owner]/[repo]/[branch]/collection/[name]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/[owner]/[repo]/[branch]/configuration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[owner]/[repo]/[branch]/configuration">> = Specific
  const handler = {} as typeof import("../../../app/(main)/[owner]/[repo]/[branch]/configuration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/[owner]/[repo]/[branch]/file/[name]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[owner]/[repo]/[branch]/file/[name]">> = Specific
  const handler = {} as typeof import("../../../app/(main)/[owner]/[repo]/[branch]/file/[name]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/[owner]/[repo]/[branch]/media/[name]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[owner]/[repo]/[branch]/media/[name]">> = Specific
  const handler = {} as typeof import("../../../app/(main)/[owner]/[repo]/[branch]/media/[name]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/[owner]/[repo]/[branch]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[owner]/[repo]/[branch]">> = Specific
  const handler = {} as typeof import("../../../app/(main)/[owner]/[repo]/[branch]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/[owner]/[repo]/[branch]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[owner]/[repo]/[branch]/settings">> = Specific
  const handler = {} as typeof import("../../../app/(main)/[owner]/[repo]/[branch]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/[owner]/[repo]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[owner]/[repo]">> = Specific
  const handler = {} as typeof import("../../../app/(main)/[owner]/[repo]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/(main)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(main)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/(main)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/[owner]/[repo]/[branch]/actions/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[owner]/[repo]/[branch]/actions/[runId]">> = Specific
  const handler = {} as typeof import("../../../app/api/[owner]/[repo]/[branch]/actions/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/[owner]/[repo]/[branch]/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[owner]/[repo]/[branch]/actions">> = Specific
  const handler = {} as typeof import("../../../app/api/[owner]/[repo]/[branch]/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/[owner]/[repo]/[branch]/branches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[owner]/[repo]/[branch]/branches">> = Specific
  const handler = {} as typeof import("../../../app/api/[owner]/[repo]/[branch]/branches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/[owner]/[repo]/[branch]/cache/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[owner]/[repo]/[branch]/cache">> = Specific
  const handler = {} as typeof import("../../../app/api/[owner]/[repo]/[branch]/cache/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/[owner]/[repo]/[branch]/collections/[name]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[owner]/[repo]/[branch]/collections/[name]">> = Specific
  const handler = {} as typeof import("../../../app/api/[owner]/[repo]/[branch]/collections/[name]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/[owner]/[repo]/[branch]/entries/[path]/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[owner]/[repo]/[branch]/entries/[path]/history">> = Specific
  const handler = {} as typeof import("../../../app/api/[owner]/[repo]/[branch]/entries/[path]/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/[owner]/[repo]/[branch]/entries/[path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[owner]/[repo]/[branch]/entries/[path]">> = Specific
  const handler = {} as typeof import("../../../app/api/[owner]/[repo]/[branch]/entries/[path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/[owner]/[repo]/[branch]/files/[path]/rename/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[owner]/[repo]/[branch]/files/[path]/rename">> = Specific
  const handler = {} as typeof import("../../../app/api/[owner]/[repo]/[branch]/files/[path]/rename/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/[owner]/[repo]/[branch]/files/[path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[owner]/[repo]/[branch]/files/[path]">> = Specific
  const handler = {} as typeof import("../../../app/api/[owner]/[repo]/[branch]/files/[path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/[owner]/[repo]/[branch]/media/[name]/[path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[owner]/[repo]/[branch]/media/[name]/[path]">> = Specific
  const handler = {} as typeof import("../../../app/api/[owner]/[repo]/[branch]/media/[name]/[path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/[owner]/[repo]/[branch]/references/[name]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[owner]/[repo]/[branch]/references/[name]">> = Specific
  const handler = {} as typeof import("../../../app/api/[owner]/[repo]/[branch]/references/[name]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/app/version/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/app/version">> = Specific
  const handler = {} as typeof import("../../../app/api/app/version/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/[...all]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...all]">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/[...all]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/collaborator-invites/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collaborator-invites/[token]">> = Specific
  const handler = {} as typeof import("../../../app/api/collaborator-invites/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/collaborators/[...slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collaborators/[...slug]">> = Specific
  const handler = {} as typeof import("../../../app/api/collaborators/[...slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/github-app/install/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github-app/install">> = Specific
  const handler = {} as typeof import("../../../app/api/github-app/install/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/repos/[owner]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/repos/[owner]">> = Specific
  const handler = {} as typeof import("../../../app/api/repos/[owner]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/webhook/github/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook/github">> = Specific
  const handler = {} as typeof import("../../../app/api/webhook/github/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(auth)/sign-in/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/sign-in/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/[owner]/[repo]/[branch]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[owner]/[repo]/[branch]">> = Specific
  const handler = {} as typeof import("../../../app/(main)/[owner]/[repo]/[branch]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/[owner]/[repo]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[owner]/[repo]">> = Specific
  const handler = {} as typeof import("../../../app/(main)/[owner]/[repo]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(main)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
